version: '3.4'

services:
  alkhairi:
    image: alkhairi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 2703:2703
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
